---
development:
  cloud_name: dmfclza05
  api_key: '571971279776778'
  api_secret: njae_9HqdDyfYWbOmLpXejZSzg4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dmfclza05
  api_key: '571971279776778'
  api_secret: njae_9HqdDyfYWbOmLpXejZSzg4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dmfclza05
  api_key: '571971279776778'
  api_secret: njae_9HqdDyfYWbOmLpXejZSzg4
  enhance_image_tag: true
  static_image_support: false